### ISSUE TITLE
Highres-cortex tests uses files in sources

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#165] opened 2020-10-12 12:36 UTC
With casa-distro 3.0, running tests for Highres-cortex in a user environment lead to an error because the following file is not found : `/casa/host/src/highres-cortex/master/tests/test_all_scripts.sh`. We should only use files that are installed tests. Or, we must find a way to perform some tests only in development environments.

**Comment by sapetnioc** [comment] 2021-02-05 07:54
This issue seems to be resolved. No ?

**Comment by ylep** [comment] 2021-02-05 08:27
Duplicate of https://github.com/neurospin/highres-cortex/issues/10
Fixed in https://github.com/neurospin/highres-cortex/commit/5ef2f36607e828b6e997d3a55948f8594a1adc09

**Closed by ylep** 2021-02-05 08:27 UTC
Labels: bug, v3.0
