### ISSUE TITLE
anatomist build issue due libGL dependency and missing undefined symbol _glapi_tls_Current

### ISSUE THREAD

**Issue by nsouedet** [brainvisa/casa-distro#113] opened 2020-09-08 10:28 UTC
Anatomist build fails at link time due to wrong libGL used. This is due to singularity that defaulty add the /.singularity.d/libs path to LD_LIBRARY_PATH. The --nv option given to singularity has the consequence to expose wrong libGL and nvidia library. A work around is to add the option container_options="--no-nv" to the casa_distro 3.0 command line. But this should be fixed to always work.

**Comment by sapetnioc** [comment] 2020-09-08 11:14
In casa_distro 3, It has been decided to automatically generate gui related options if `gui=yes` option is used (this is the default in `run` command). This avoid to write required gui options in all users config files. That way if the required option must be changed in later Singularity version, only the casa_distro code will need to be updated.

Therefore, resolving this issue could be done by choosing appropriate behavior and default values for `gui` options. We discussed about an evolution of the `gui` value that could become an enum instead of a boolean. For instance :

- `gui=no` : would add `--no-nv` to Singularity options
- `gui=gpu` : would add `--nv` to Singularity options
- `gui=cpu` : would set `LD_LIBRARY_PATH` to use software OpenGL rendering.

That said, would it be enough for this issue to have gui activated by default for `run` or `shell` command and disabled for `bv_maker` command ? There is still a risk of wrong building if someone perform build through gui ennabled commands. Another option would be to add to `bv_maker` specific code for checking OpenGL libraries when used inside `casa-ditro`.

**Comment by ylep** [comment] 2020-09-09 09:37
I don't think that we can rely on the `gui` option to be correctly set, because we may always run bv_maker inside of a `casa_distro shell` and the shell *should* be GUI-enabled by default. We should instead ignore /.singularity.d/libs in the build system, it is part of CMake to account for idiosyncrasies of common setups.

**Comment by denisri** [comment] 2020-10-07 13:32
We had this issue yesterday once again. I have not redone the full process but I suspect what happens:
- either `cmake` doesn't care about the `libGL` currently in the `LD_LIBRARY_PATH` and always choses `/usr/lib/x86_64/libGL.so`, or the config has been done while using `casa_distro bv_maker` (with `gui=false`)
- then we are using `casa_distro shell` (with `gui=true`) to do several things, and eventually use `bv_maker`. Then the nvidia libs are in the paths, and links fails.

* on ubuntu 18 hosts, things seem OK because there is now a single libGL implementation which switches between the nvidia and mesa/DRI implementations - in other words the nvidia driver is made available when `gui=true`, but the libGL and its api is the same.
* on ubuntu 16 hosts, nvidia and system libGL are completely different.

The problem happens when linking the libs, not during configure/cmake, thus changing temporarily `LD_LIBRARY_PATH` while calling `cmake` will not solve the issue. And we cannot change it during `make`, which is often called manually.

If we _always_ use `gui=true`, then forcing the use of nvidia libs (by editing `CMakeCache.txt`) solves the problem, but it's not a general solution. I think we should rather use the system libGL, but then we seem to need to link against additional libraries (libGLdispatch ? libGLX ?) which are not setup by cmake.

**Comment by denisri** [comment] 2020-10-07 15:48
brainvisa/anatomist-free@187d854b15f9b9c21eccf278d55a8f87bfcee3d2 is an attempt to fix this (by linking additionally with libGLX) but has to be tested in a situation where the problem occurs (I could not reproduce it).

**Comment by denisri** [comment] 2021-01-21 15:44
I would like to come back on this problem.
If I am correct, the problem happens only on Ubuntu 16.04 hosts, where the libGL implementation is very different from the one on Ubuntu 18.04.
It has been fixed in 2 different ways:
1. linking against libGLX to include missing libraries (at least attempt)
2. blocking `bv_maker build` in containers started with nvidia drivers, and asking to restart with `opengl=container`

As a matter of fact, I don't know if solution 1 worked or not (I had no feedback and could not test it myself), and I admit that I find solution 2 very annoying because it forces me to restart shells everytime whereas I used to work in a container shell with GUI/openGL enabled. Moreover I think it is not useful on Ubuntu >= 18.04 hosts.

So I am asking if we could temporarily disable solution 2 and have someone with a Ubuntu 16.04 system, and who ran into this problem, test solution 1 ?

**Comment by sapetnioc** [comment] 2021-02-05 08:10
I can perforim some tests in Neurospin to try to reproduce the bug. But I may need some help to clearly understand what test I should do. In parallel I am trying someone with this Ubuntu 16.04 configuration in CATI.

**Comment by denisri** [comment] 2021-02-05 08:46
bv_maker has been locked to avoid this situation (it refuses to run if nvidia drivers are available in singularity). If you need to test things, I have added a hook to unkock this, by setting the env variable `BV_MAKER_BYPASS_SINGULARITY_LIB_PATH` to 1.
However I have never run into this situation and I don't know how to reproduce it, and I think some people have had problems at link time, while others have had undefined symbols at run time. But I'm not really sure.

**Comment by denisri** [comment] 2021-02-05 14:29
we activate the workaround by default

**Comment by denisri** [comment] 2021-02-08 16:06
we have devided to activate the workaround by default

**Comment by denisri** [comment] 2021-02-08 16:09
done in  brainvisa/brainvisa-cmake@dc460f157fcb14dd1a06577a0d4aab3e837e918e

**Comment by denisri** [comment] 2021-02-08 16:09
We'll reopen if we still experience problems.

**Closed by denisri** 2021-02-08 16:09 UTC
